//generated app.quicktype.io with some tweaks 
export type playerCompleteType = {
    Rk:                         number;
    Player:                     string;
    Nation:                     string;
    Pos:                        string;
    Squad:                      string;
    Comp:                       string;
    Age:                        number | string;
    Born:                       number | string;
    MP:                         number;
    Starts:                     number;
    Min:                        number;
    "90s":                      number;
    Gls:                        number;
    Ast:                        number;
    "G+A":                      number;
    "G-PK":                     number;
    PK:                         number;
    PKatt:                      number;
    CrdY:                       number;
    CrdR:                       number;
    xG:                         number;
    npxG:                       number;
    xAG:                        number;
    "npxG+xAG":                 number;
    "G+A-PK":                   number;
    "xG+xAG":                   number;
    PrgC:                       number;
    PrgP:                       number;
    PrgR:                       number;
    Sh:                         number;
    SoT:                        number;
    "SoT%":                     number | string;
    "Sh/90":                    number;
    "SoT/90":                   number;
    "G/Sh":                     number | string;
    "G/SoT":                    number | string;
    Dist:                       number | string;
    FK:                         number;
    PK_stats_shooting:          number;
    PKatt_stats_shooting:       number;
    xG_stats_shooting:          number;
    npxG_stats_shooting:        number;
    "npxG/Sh":                  number | string;
    "G-xG":                     number | string;
    "np:G-xG":                  number | string;
    Cmp:                        number;
    Att:                        number;
    "Cmp%":                     number | string;
    TotDist:                    number;
    PrgDist:                    number;
    Ast_stats_passing:          number;
    xAG_stats_passing:          number;
    xA:                         number;
    "A-xAG":                    number | string;
    KP:                         number;
    "1/3":                      number;
    PPA:                        number;
    CrsPA:                      number;
    PrgP_stats_passing:         number;
    Live:                       number;
    Dead:                       number;
    FK_stats_passing_types:     number;
    TB:                         number;
    Sw:                         number;
    Crs:                        number;
    TI:                         number;
    CK:                         number;
    In:                         number;
    Out:                        number;
    Str:                        number;
    Cmp_stats_passing_types:    number;
    Tkl:                        number;
    TklW:                       number;
    "Def 3rd":                  number;
    "Mid 3rd":                  number;
    "Att 3rd":                  number;
    Att_stats_defense:          number;
    "Tkl%":                     number | string;
    Lost:                       number;
    Blocks_stats_defense:       number;
    Sh_stats_defense:           number;
    Pass:                       number;
    Int:                        number;
    "Tkl+Int":                  number;
    Clr:                        number;
    Err:                        number;
    SCA:                        number;
    SCA90:                      number;
    PassLive:                   number;
    PassDead:                   number;
    TO:                         number;
    Sh_stats_gca:               number;
    Fld:                        number;
    Def:                        number;
    GCA:                        number;
    GCA90:                      number;
    Touches:                    number;
    "Def Pen":                  number;
    "Def 3rd_stats_possession": number;
    "Mid 3rd_stats_possession": number;
    "Att 3rd_stats_possession": number;
    "Att Pen":                  number;
    Live_stats_possession:      number;
    Att_stats_possession:       number;
    Succ:                       number;
    "Succ%":                    number | string;
    Tkld:                       number;
    "Tkld%":                    number | string;
    Carries:                    number;
    TotDist_stats_possession:   number;
    PrgDist_stats_possession:   number;
    PrgC_stats_possession:      number;
    "1/3_stats_possession":     number;
    CPA:                        number;
    Mis:                        number;
    Dis:                        number;
    Rec:                        number;
    PrgR_stats_possession:      number;
    CrdY_stats_misc:            number;
    CrdR_stats_misc:            number;
    "2CrdY":                    number;
    Fls:                        number;
    Fld_stats_misc:             number;
    Off_stats_misc:             number;
    Crs_stats_misc:             number;
    Int_stats_misc:             number;
    TklW_stats_misc:            number;
    PKwon:                      number;
    PKcon:                      number;
    OG:                         number;
    Recov:                      number;
    Won:                        number;
    Lost_stats_misc:            number;
    "Won%":                     number | string;
    GA:                         number | string;
    GA90:                       number | string;
    SoTA:                       number | string;
    Saves:                      number | string;
    "Save%":                    number | string;
    W:                          number | string;
    D:                          number | string;
    L:                          number | string;
    CS:                         number | string;
    "CS%":                      number | string;
    PKatt_stats_keeper:         number | string;
    PKA:                        number | string;
    PKsv:                       number | string;
    PKm:                        number | string;
    PSxG:                       number | string;
    "PSxG/SoT":                 number | string;
    "PSxG+/-":                  number | string;
    "/90":                      number | string;
    Cmp_stats_keeper_adv:       number | string;
    Att_stats_keeper_adv:       number | string;
    "Cmp%_stats_keeper_adv":    number | string;
    "Att (GK)":                 number | string;
    Thr:                        number | string;
    "Launch%":                  number | string;
    AvgLen:                     number | string;
    Opp:                        number | string;
    Stp:                        number | string;
    "Stp%":                     number | string;
    "#OPA":                     number | string;
    "#OPA/90":                  number | string;
    AvgDist:                    number | string;
}